#!/usr/bin/env bash

echo -e "\nEnter commit message :"
read message

echo -e "\nPulling the lastest changes:"
git pull

echo -e "\nAdding & committing the new changes:"
git add .
git commit -m "${message}"

echo -e "\nPushing the new changes:"
git push
